## Numpy

In [44]:
# import numpy

import numpy as np

In [45]:
my_list = [1, 2, 3, 4, 5]

arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


In [46]:
type(arr) # returns a numpy array

numpy.ndarray

In [47]:
arr # one dimentional array

array([1, 2, 3, 4, 5])

In [48]:
arr.shape # shows num of rows & columns

(5,)

In [49]:
## Multinested array
my_lst1 = [1, 2, 3, 4, 5]
my_lst2 = [2, 3, 4, 5, 6]
my_lst3 = [9, 7, 6, 8, 9]

arr = np.array([my_lst1, my_lst2, my_lst3])

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [50]:
arr.shape # two dimentional, 2 brackets [[...]]

(3, 5)

In [51]:
arr.reshape(5, 3) # change shape of array

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

# Indexing

In [52]:
## Accessing the elements
arr_index = np.array([1, 2, 3, 4, 5])
arr_index[3]

np.int64(4)

In [ ]:
## Splicing - One dimentional
arr_index[1:3] # start at index 1, stop at excluding index 3

array([2, 3])

In [ ]:
## Splicing - Two dimentional
arr[1:3] # indexes at specific rows, starts at index row 1, ends at excluding row 3

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [56]:
## Another example
arr[0:2, 0:2] # indexes specific rows AND specific columns, starting at 0 and ends excluding index 2

array([[1, 2],
       [2, 3]])

In [ ]:
## Arange - similar to range but returns Numpy array instead of list
arr = np.arange(0, 10, step=2)
arr

array([0, 2, 4, 6, 8])

In [60]:
## Linspace - similar to arange but returns sequences of numbers
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [62]:
## Conditionals
val = 2
arr [arr< 2] # returns all values greater than 2

array([0])

In [63]:
## Ones - create array of specified shape and data type
np.ones((2, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
## Random Distribution
np.random.rand(3, 3)

array([[0.53739673, 0.88758833, 0.88345557],
       [0.45942358, 0.50181303, 0.94894638],
       [0.98676938, 0.07612986, 0.24927245]])